name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run unit tests
      run: |
        go test ./...

    - name: Build Docker image
      run: |
        docker build -t yourusername/tracker-app .

    # Optional: push to Docker Hub
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag yourusername/tracker-app yourusername/tracker-app:latest
        docker push yourusername/tracker-app:latest
